### ISSUE TITLE
version 2.0

### ISSUE THREAD

**Issue by xan2622** [CreativeTools/ct-pipe-dream#2]
Do you plan to update your script to 2.0 ?

I know that an update has been made by Neil Blevins at http://www.neilblevins.com/cg_tools/scripts/3dsmax/soulburnscripts.htm but this SoulBurnscripts package contains many scripts that users might not want to use/install.

Of course, it's still possible to delete the scripts that we don't want (once the SoulBurnscripts is installed) but it's a little bit annoying to have to install a bundle for only one script...

Would it be possible to update the http://www.scriptspot.com/3ds-max/scripts/pipedream page with a version 2.0 that features Neil Blevins additions ? Maybe you could ask Neil Blevins' consent (to add his extra options). If you credit him and give a link to his website, maybe he would agree ?

Or maybe you could ask Neil Blevins to create a scriptspot page (named _pipeMaker_ ?) but without all the Soulburnscripts package? 

argh, I hope this could be possible (a maxscript 2.0 version).

**Comment by teppix** [comment]
There is no 2.0 of this script. Neil's version is a fork, and not a direct successor.

If he wishes to distribute the script separately, it is up to him to do so. If you want to encourage him to publish his scripts on github for easier access, please do so, that would be greatly appreciated! We provide the code for free, but we won't chase after him for his improvements. If he wants to contribute back, he's more than welcome to do it.

The proper way to do it would be for him to make a fork of this repository and make the changes there, if the changes are reasonable, there might be a possibility for pulling his changes back. If there are many changes, I think it might be more reasonable for Neil to maintain the fork himself.
